import { readFileSync, readdirSync, existsSync } from "fs";
import { join, basename } from "path";
import type { ParsedSkill, PlatformId } from "../types.js";

// ---------------------------------------------------------------------------
// SKILL.md parser
// ---------------------------------------------------------------------------

/**
 * Parse a single SKILL.md file into a structured object.
 */
export function parseSkill(skillDir: string): ParsedSkill | null {
  const skillPath = join(skillDir, "SKILL.md");
  if (!existsSync(skillPath)) return null;

  const raw = readFileSync(skillPath, "utf-8");
  const dirName = basename(skillDir);

  // Extract YAML frontmatter
  const fmMatch = raw.match(/^---\n([\s\S]*?)\n---\n([\s\S]*)$/);
  if (!fmMatch) {
    return {
      dirName,
      name: dirName,
      description: "",
      userInvocable: true,
      body: raw,
      raw,
    };
  }

  const frontmatter = fmMatch[1];
  const body = fmMatch[2];

  const name = extractYamlField(frontmatter, "name") || dirName;
  const description = extractYamlField(frontmatter, "description") || "";
  const userInvocable = extractYamlField(frontmatter, "user-invocable") !== "false";

  return { dirName, name, description, userInvocable, body, raw };
}

/**
 * Parse all skills from a skills/ directory.
 */
export function parseAllSkills(skillsRoot: string): ParsedSkill[] {
  if (!existsSync(skillsRoot)) return [];

  const dirs = readdirSync(skillsRoot, { withFileTypes: true })
    .filter((d) => d.isDirectory())
    .map((d) => d.name)
    .sort();

  const skills: ParsedSkill[] = [];
  for (const dir of dirs) {
    const skill = parseSkill(join(skillsRoot, dir));
    if (skill) skills.push(skill);
  }
  return skills;
}

// ---------------------------------------------------------------------------
// Platform-specific compilation
// ---------------------------------------------------------------------------

/**
 * Compile a skill for a specific platform format.
 */
export function compileSkill(skill: ParsedSkill, platformId: PlatformId): string {
  switch (platformId) {
    case "cursor":
      return compileCursorMdc(skill);
    case "windsurf":
    case "roo-code":
      return compileMarkdownRule(skill);
    case "copilot":
      return compileCopilotSection(skill);
    case "opencode":
    case "codex":
      return compileAgentsMdSection(skill);
    case "antigravity":
      return compileMarkdownRule(skill);
    case "claude-code":
      return skill.raw; // pass-through
    default:
      return compileMarkdownRule(skill);
  }
}

/**
 * Compile all skills into a single combined document (for platforms
 * that use a single instructions file, like Copilot or AGENTS.md).
 */
export function compileSkillsToSingleDoc(
  skills: ParsedSkill[],
  platformId: PlatformId,
  maxLines?: number,
): string {
  const header = `# coding-friend Rules\n\nAuto-generated by coding-friend. Do not edit manually.\n\n`;
  const sections = skills.map((s) => compileSkill(s, platformId));
  let doc = header + sections.join("\n---\n\n");

  if (maxLines) {
    const lines = doc.split("\n");
    if (lines.length > maxLines) {
      doc = lines.slice(0, maxLines).join("\n") + "\n\n<!-- truncated -->\n";
    }
  }

  return doc;
}

// ---------------------------------------------------------------------------
// Format: Cursor .mdc
// ---------------------------------------------------------------------------

function compileCursorMdc(skill: ParsedSkill): string {
  const frontmatter = [
    "---",
    `description: ${skill.description}`,
    "globs:",
    `alwaysApply: ${skill.userInvocable ? "false" : "true"}`,
    "---",
  ].join("\n");

  return `${frontmatter}\n${skill.body}`;
}

// ---------------------------------------------------------------------------
// Format: Generic markdown rule (Windsurf, Roo Code, Antigravity)
// ---------------------------------------------------------------------------

function compileMarkdownRule(skill: ParsedSkill): string {
  const header = `<!-- coding-friend: ${skill.name} -->\n`;
  return header + skill.body;
}

// ---------------------------------------------------------------------------
// Format: Copilot instructions section
// ---------------------------------------------------------------------------

function compileCopilotSection(skill: ParsedSkill): string {
  return `## ${skill.name}\n\n${skill.description}\n${skill.body}`;
}

// ---------------------------------------------------------------------------
// Format: AGENTS.md section (OpenCode, Codex)
// ---------------------------------------------------------------------------

function compileAgentsMdSection(skill: ParsedSkill): string {
  return `## ${skill.name}\n\n${skill.description}\n${skill.body}`;
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function extractYamlField(yaml: string, field: string): string | undefined {
  const match = yaml.match(new RegExp(`^${field}:\\s*(.+)$`, "m"));
  return match?.[1]?.trim();
}
